django_p2l/urls.py
from django.contrib import admin
from django.urls import path, include
from django.contrib.staticfiles.storage import staticfiles_storage
from django.views.generic.base import RedirectView

urlpatterns = [
    # Admin
    path('admin/doc/', include('django.contrib.admindocs.urls')),
    path('admin/', admin.site.urls),

    # Favicon
    path('favicon.ico', RedirectView.as_view(url=staticfiles_storage.url('image/favicon.ico'))),

    # Local Apps
    path('', include('pages.urls')),
    path('', include('games.urls')),

    # User Management
    path('account/', include('users.urls')),
    path('account/', include('allauth.urls')),
]

games/urls.py
from django.urls import path
from django.contrib.auth.decorators import login_required

from .views import MathGameView, AnagramGameView, GameScoresView, record_score

app_name = 'games'
urlpatterns = [
    path('math-game/', login_required(MathGameView.as_view()), name='math-game'),
    path('anagram-game/', login_required(AnagramGameView.as_view()), name='anagram-game'),
    path('record-score/', record_score, name='record_score'),
    path('game-scores/', GameScoresView.as_view(), name='game-scores'),
]

pages/urls.py
from django.urls import path
from . import views

from .views import AboutUsView, HomePageView, ReviewPageView, user_review

app_name = 'pages'
urlpatterns = [
    path('', HomePageView.as_view(), name='homepage'),
    path('about-us/', AboutUsView.as_view(), name='about-us'),
    path('contact/', views.contact, name='contact'),
    path('review/', ReviewPageView.as_view(), name="review"),
    path('review/record-review', user_review, name='user_review'),
    path('record-review/', user_review, name='user_review'),
]

templates/_base.html
{% load static %}
<!DOCTYPE html>
{% block html %}
<html lang="en">
<head>
{% block head %}
<meta charset="UTF-8">
<meta name="viewport" content="width=device-width, initial-scale=1">
<link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap@4.6.2/dist/css/bootstrap.min.css" integrity="sha384-xOolHFLEh07PJGoPkLv1IbcEPTNtaed2xpHsD9ESMhqIYd0nLMwNLD69Npy4HI+N" crossorigin="anonymous">
<link rel="stylesheet" href="{% static 'css/main.css' %}">
<script src="https://kit.fontawesome.com/b48ff8a378.js" crossorigin="anonymous"></script>
<title>{% block title %}{% endblock %} | Play to Learn</title>
{% endblock %}
</head>
<body>
{% block body %}
    <header>
        <nav class="navbar navbar-expand-sm navbar-dark bg-dark fixed-top" id="topNav">
            <div class="container-fluid">
                <a class="navbar-brand" href="{% url 'pages:homepage' %}">LTP</a>
                <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarResponsive">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="collapse navbar-collapse" id="navbarResponsive">
                    <ul class="navbar-nav ml-auto">
                        <li class="nav-item active">
                            <a class="nav-link" href="{% url 'pages:homepage' %}">Home</a>
                        </li>
                        {% if not user.is_authenticated %}
                            <li class="nav-item">
                                <a class="nav-link" href="{% url 'account_login' %}">Log in</a>
                            </li>
                            <li class="nav-item">
                                <a class="nav-link" href="{% url 'account_signup' %}">Sign up</a>
                            </li>
                        {% else %}
                            <li class="nav-item dropdown" id="navDropdown">
                                <a href="#" class="nav-link dropdown-toggle" data-toggle="dropdown" 
                                        aria-haspopup="true" aria-expanded="false">Games</a>
                                <ul class="dropdown-menu" aria-labelledby="navDropdown">
                                    <li class="nav-item dropdown">
                                        <a class="dropdown-item" href="{% url 'games:anagram-game' %}">Anagram Hunt</a>
                                    </li>
                                    <li class="nav-item dropdown">
                                        <a class="dropdown-item" href="{% url 'games:math-game' %}">Math Facts Practice</a>
                                    </li>
                                    <li class="nav-item dropdown">
                                        <a href="{% url 'games:game-scores' %}" class="dropdown-item">Leaderboard</a>
                                    </li>
                                </ul>
                            </li>
                            <li class="nav-item dropdown">
                                <a class="nav-link dropdown-toggle" href="#" id="navbarDropdown" 
                                role="button" data-toggle="dropdown" aria-haspopup="true"
                                aria-expanded="false">
                                Profile
                                </a>
                                <div class="dropdown-menu" aria-labelledby="navbarDropdown">
                                    <a class="dropdown-item" href="{% url 'my-account' %}">My Account</a>
                                    <a class="dropdown-item" href="{% url 'my-scores' %}">My Scores</a>
                                    <div class="dropdown-divider"></div>
                                    <form method="post" action="{% url 'account_logout' %}">
                                        {% csrf_token %}
                                        <button class="btn dropdown-item">Log out</button>
                                    </form>
                                </div>
                            </li>
                            <li class="nav-item"><a class="nav-link" href="{% url 'pages:review' %}">Reviews</a></li>
                        {% endif %}
                        <li class="nav-item">
                        <a class="nav-link" href="{% url 'pages:about-us' %}">About</a>
                        </li>
                    </ul>
                </div>
            </div>
        </nav>
    </header>
{% if messages %}
    <ul>
        {% for message in messages %}
            <div class="alert message{{ message.tags }} alert-dismissible" role="alert">
                <strong>{{message}}</strong>
                <button type="button" class="close" data-dismiss="alert"
                    aria-label="Close">
                    <i class="fas fa-window-close"></i>
                </button>
            </div>
        {% endfor %}
    </ul>
{% endif %}
{% block main %}{% endblock %}
<footer class="fixed-bottom bg-light">
    <div class="row">
        <div class="float-left m-1 mr-2 col">Copyright &copy; 2020 Play to Learn.</div>
        <div class="col float-right">
            <ul class="list-unstyled">
                <li class="float-right">
                    <a class="nav-link" href="{% url 'pages:contact' %}">Contact</a>
                </li>
                {% if user.is_staff %}
                <li class="nav-item float-right">
                    <a class="nav-link" href="/admin/">Admin</a>
                </li>
                {% endif %}
            </ul>
        </div>
    </div>
</footer>
<script src="https://cdn.jsdelivr.net/npm/jquery@3.5.1/dist/jquery.slim.min.js" integrity="sha384-DfXdz2htPH0lsSSs5nCTpuj/zy4C+OGpamoFVy38MVBnE+IbbVYUew+OrCXaRkfj" crossorigin="anonymous"></script>
<script src="https://cdn.jsdelivr.net/npm/bootstrap@4.6.2/dist/js/bootstrap.bundle.min.js" integrity="sha384-Fy6S3B9q64WdZWQUiU+q4/2Lc9npb8tCaSX9FK7E8HnRr0Jz8D6OP9dO5Vg3Q9ct" crossorigin="anonymous"></script>
{% endblock %}
</body>
</html>
{% endblock %}

templates/_base_vue.html
{% extends '_base.html' %}

{% block html %}
<!DOCTYPE html>
<html lang="">
  <head>
    {% block head %}{{ block.super }}{% endblock %}
  <script defer src="http://localhost:8080/js/chunk-vendors.js"></script><script defer src="http://localhost:8080/js/app.js"></script></head>
  <body>
  {% block body %}
    {{ block.super }}
    <noscript>
      <strong>We're sorry but vue-games doesn't work properly without JavaScript enabled. Please enable it to continue.</strong>
    </noscript>
    <div id="app"></div>
    <!-- built files will be auto injected -->
  {% endblock body %}
  </body>
</html>
{% endblock html %}

templates/anagram-game.html
{% extends '_base_vue.html' %}

{% block title %}Anagram Hunt{% endblock %}
{% block main %}

{% endblock %}

templates/game-scores.html
{% extends '_base_vue.html' %}

{% block title %}Game Scores{% endblock %}
{% block main %}
<h1 class="text-center">Game Scores</h1>
<hr>
<h2 class="text-center">Math Facts</h2>
  <table class="table m-auto w-75">
        <thead>
            <tr>
                <th scope="col" class="text-center">User</th>
                <th scope="col" class="text-center">Score</th>
                <th scope="col" class="text-center">Operation</th>
                <th scope="col" class="text-center">Max Number</th>
                <th scope="col" class="text-center">Date</th>
            </tr>
        </thead>
        <tbody>
            {% for score in math_scores %}
                <tr>
                    <td class="text-center">{{ score.user_name }}</td>
                    <td class="text-center">{{ score.score }}</td>
                    <td class="text-center">{{ score.operation }}</td>
                    <td class="text-center">{{ score.max_number }}</td>
                    <td class="text-center">{{ score.created }}</td>
                </tr>
            {% endfor %}
        </tbody>
    </table>
    <hr>
<h2 class="text-center">Anagram Hunt</h2>
    <table class="table m-auto w-75">
        <thead>
            <tr>
                <th scope="col" class="text-center">User</th>
                <th scope="col" class="text-center">Score</th>
                <th scope="col" class="text-center">Date</th>
            </tr>
        </thead>
        <tbody>
            {% for score in anagram_scores %}
                <tr>
                    <td class="text-center">{{ score.user_name }}</td>
                    <td class="text-center">{{ score.score }}</td>
                    <td class="text-center">{{ score.created }}</td>
                </tr>
            {% endfor %}
        </tbody>
    </table>
{% endblock %}

templates/math-game.html
{% extends '_base_vue.html' %}

{% block title %}Math Facts{% endblock %}
{% block main %}

{% endblock %}

templates/review_form.html
{% extends '_base_vue.html' %}

{% block title %}Share your opinion!{% endblock %}
{% block main %}

{% endblock %}